=== HarshalShende/Shift-The-Code/PRESIDENT.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT LIST (PRESIDENT+)>
<!ELEMENT PRESIDENT (NAME,TERM,PARTY,HOMESTATE)>
<!ELEMENT NAME (FIRST,MIDDLE,LAST)>
<!ELEMENT FIRST (#PCDATA)>
<!ELEMENT MIDDLE (#PCDATA)>
<!ELEMENT LAST (#PCDATA)>
<!ELEMENT TERM (TERMSTART,TERMEND,TERMLENGTH)>
<!ELEMENT TERMSTART (#PCDATA)>
<!ELEMENT TERMEND (#PCDATA)>
<!ELEMENT TERMLENGTH (#PCDATA)>
<!ELEMENT PARTY (#PCDATA)>
<!ELEMENT HOMESTATE (#PCDATA)>

=== HarshalShende/Shift-The-Code/PRESIDENT.xml
<!DOCTYPE LIST SYSTEM "E:\XML WEBSERVICES\PRESIDENT.dtd">
<LIST>
<PRESIDENT>
<NAME>
<FIRST>GEORGE</FIRST>
<MIDDLE />
<LAST>WASHINGTON</LAST>
</NAME>
<TERM>
<TERMSTART>1789</TERMSTART>
<TERMEND>1797</TERMEND>
<TERMLENGTH>6</TERMLENGTH>
</TERM>
<PARTY>N/A</PARTY>
<HOMESTATE>VIRGINIA</HOMESTATE>
</PRESIDENT>
</LIST>
