=== HarshalShende/Shift-The-Code/Repractice/books2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT books (book*)>
<!ELEMENT book ((bookname|title),price,author+,publication?)>
<!ELEMENT bookname (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publication (#PCDATA)>

=== HarshalShende/Shift-The-Code/Repractice/books2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "E:\XML WEBSERVICES\Repractice\books2.dtd">
<books>
    <book>
        <bookname>core java</bookname>
        <price>1000</price>
        <author>HAri Krishna</author>
        <publication>Naresh IT</publication>
    </book>
    
    <book>
        <title>CJ</title>
        <price>2000</price>
        <author>Natraj</author>
        <publication>Naresh IT</publication>
    </book>
</books>
