<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees[
<!ELEMENT employees (employee*)>
<!ELEMENT employee ANY>
<!ELEMENT name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
]>

<employees>
    <!-- Mixed -->
    <employee>
        Name: <name>Hanuman</name>
        Saary: <salary>654465456654</salary>
    </employee>
    
    <!-- Text ONLY -->
    <employee>Hello World</employee>
    
    <!-- EMPTY -->
    <employee></employee>
    
    <!-- Child Obnly -->
    <employee>
        <salary>12000</salary>
    </employee>
</employees>
